version: 0.2

phases:
  install:
    runtime-versions:
      dotnet:4.6
  pre_build:
    commands:
     - nuget restore
  build:
    commands:
     - msbuild CRUDDemo.sln /t:Rebuild /p:Configuration=Release
artifacts:
  files:
    - '**/*'

  
