version: 0.2

phases:
  install:
    runtime-versions:
      sdk: 4.7.2    
  build:
    commands:
      - nuget restore
      - msbuild CRUDDemo.sln /t:Rebuild /p:Configuration=Release
artifacts:
  files:
    - '**/*'


  
