version: 0.2
phases:
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - nuget restore
      - msbuild 
artifacts:
  files:
    - '**/*'
  base-directory: 'C:\codebuild\artifacts\_PublishedWebsites\CRUDDemo\'
