version: 0.2

phases:
  pre_build:
    commands:
     - New-Item -ItemType Junction -Path C:\Src -Value $Env:CODEBUILD_SRC_DIR
     - cd C:\Src  
     - nuget.exe restore
  build:
    commands:
     - msbuild /t:rebuild /p:outdir="c:\outproject\\" /p:Configuration=Release
     
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    artifact1:      
      files:
        - '**/*'
      base-directory: 'c:\outproject\_PublishedWebsites\CRUDDemo\'
    artifact2:      
      files:
        - appspec.yml
      base-directory: $Env:CODEBUILD_SRC_DIR
    

  
