version: 0.2

phases:
  install:
    commands:
      - Dism /online /Enable-Feature /FeatureName:NetFx4 /All
  build:
    commands:
      - nuget restore
      - msbuild CRUDDemo.sln /t:Rebuild /p:Configuration=Release
artifacts:
  files:
    - '**/*'


  
