version: 0.2    
  build:
    commands:
      - (Get-ECRLoginCommand).Password | docker login --username AWS --password-stdin 858079239489.dkr.ecr.us-east-1.amazonaws.com
      - nuget restore
      - msbuild CRUDDemo.sln /t:Rebuild /p:Configuration=Release /p:outdir="c:\buildfiles\\"
artifacts:
  files:
    - '**/*'


  
